version: '3.8'

services:
  box-tracker:
    build: .
    ports:
      - "3003:3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/data/dev.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 40s