services:
  box-tracker:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/dev.db
    restart: unless-stopped